version: "3.4"

services:
  scrape:
    image: govhawk/openstates:2.0.0
    environment:
    - MYSQL_HOST=mysql
    - DATABASE_URL=postgres://postgres:secret@postgres:5432/openstates
    - NEW_YORK_API_KEY=${NEW_YORK_API_KEY}
    - INDIANA_API_KEY=${INDIANA_API_KEY}
    - OLODATA_PASSWORD=${OLODATA_PASSWORD}
    - OLODATA_USERNAME=${OLODATA_USERNAME}
    - PUPA_ARGS=${PUPA_ARGS}
    - SKIP_BILLY=true
    - OUTPUT_TARGET=${OUTPUT_TARGET}
    - CACHE_TARGET=${CACHE_TARGET}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - AMAZON_SQS_QUEUE_PREFIX=${AMAZON_SQS_QUEUE_PREFIX}
    - AMAZON_SQS_QUEUE_SEP=${AMAZON_SQS_QUEUE_SEP}
    - AMAZON_SQS_QUEUE=${AMAZON_SQS_QUEUE}
    - AMAZON_S3_BUCKET=${AMAZON_S3_BUCKET}
    - AMAZON_S3_ALWAYS=${AMAZON_S3_ALWAYS}
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=pass1234
    - VOTE_EVENT_NO_BILL_UUID=${VOTE_EVENT_NO_BILL_UUID}
    entrypoint: /opt/openstates/openstates/pupa-scrape.sh
    depends_on:
    - mysql
    - redis
  postgres:
    image: mdillon/postgis:10-alpine
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=openstates
  dbinit:
    image: openstates/openstates
    environment:
    - DATABASE_URL=postgres://postgres:secret@postgres:5432/openstates
    entrypoint: /opt/openstates/openstates/scripts/dbinit.sh
    depends_on:
    - postgres
  mysql:
    image: mysql:5.6
    command: --max_allowed_packet=512M
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=capublic
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
  ca-download:
    image: govhawk/openstates:2.0.0
    entrypoint: /opt/openstates/openstates/openstates/ca/download.sh
    environment:
    - MYSQL_HOST=mysql
    depends_on:
    - mysql
  redis:
    image: bitnami/redis:5.0.5-ol-7-r89
    ports:
    - "6379:6379"
    environment:
    - REDIS_PASSWORD=pass1234
    restart: always

networks:
  default:
    external:
      name: mynet
