#!/bin/bash
#
# Helper script to set up local dev environment
if ! command -v python3 &> /dev/null; then
    echo " <> Oops, we need python3 installed"
fi

# Stash path to python3 interpreter
python_int_path="$(which python3)"

# @see https://stackoverflow.com/a/957978/1858091
govhawk_repo_root="$(git rev-parse --show-toplevel)"

# Store the original PYTHONPATH var for virtualenv deactivation
# @see https://stackoverflow.com/a/4758351/1858091
export GOVHAWK_TMP_ORIGINAL_PYTHON_PATH="${PYTHONPATH}"

# Set PYTHONPATH path to repo subdirectory containing
# jurisdiction scrapers
export PYTHONPATH="${govhawk_repo_root}/openstates"

# Init virtualenv if not already set up
if [ ! -f "${govhawk_repo_root}/venv/bin/activate" ]; then
    virtualenv --python="${python_int_path}" venv
fi

# Source virtualenv
# shellcheck source=/dev/null
source "${govhawk_repo_root}/venv/bin/activate"

# Deps
# Note that local_requirements.txt omits California's MySQL client dependency for now.
pip3 install -r local_requirements.txt
pip3 install flake8
pip3 install opencivicdata
pip3 install pupa

echo ""
echo ""
echo " <> GovHawk venv ready :)"
echo "   ==> Venv via ${python_int_path}"
echo "   ==> PYTHONPATH=${PYTHONPATH}"
echo "   ==> Try running 'pupa update vt bills --scrape'"
echo "   ==> Testing local pupa?, Try 'pip3 uninstall pupa -y && pip3 install local/path/to/pupa'"
echo ""
echo ""
